apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: videos
  namespace: videos
spec:
  secretName: videos
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
    - "videos.trueberryless.org"
